name: auto merge

on:
  pull_request:
    branches: [ setup ]
    
jobs:
  merge:

    runs-on: [self-hosted, linux, ARM64]
    
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.BOT }}"
